POST http://localhost:8080/v1/member/add
Content-Type: application/json

{
  "account": "hello",
  "password": "<hello>",
  "email" : "hello123"
}
###################
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "account": "hello",
  "password": "<hello>"
}

##########################
POST http://localhost:8080/login/re-connect
Content-Type: application/json

{
  "account": "hello",
  "password": "<hello>",
  "sessionCode": "d80eaca6-4e17-4b89-b590-8022a06499f4"
}

###################
