POST http://localhost:8080/v1/member/add
Content-Type: application/json

{
  "account": "hello",
  "password": "<hello>",
  "email" : "hello123"
}
###################
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "account": "hello",
  "password": "<hello>"
}

##########################
POST http://localhost:8080/login/re-connect
Content-Type: application/json

{
  "account": "hello",
  "password": "<hello>",
  "sessionCode": "61455a53-703a-475b-9f5e-284d1ed1cc07"
}

###################
