GET http://localhost:8080/hello/test?name=hello

###################

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "account": "hello",
  "password": "<hello>"
}

###################
POST http://localhost:8080/v1/member/add
Content-Type: application/json

{
  "account": "hello",
  "password": "<hello>",
  "email" : "hello123"
}